---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.base_config.appName}}
  namespace: {{ .Values.base_config.namespace}}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName}}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.base_config.appName}}
            port:
              number: 80
